### ISSUE TITLE
Fails on raspiblitz v1.7.0

### ISSUE THREAD

**Issue by shawnyeager** [pxsocs/warden_terminal#55]
After `git clone https://github.com/pxsocs/warden_terminal`, `cd warden_terminal`, `pip3 install -r requirements.txt`, I see the following warnings:

```
  The script tabulate is installed in '/home/admin/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script pyfiglet is installed in '/home/admin/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

After running `python3 node_warden.py`:

```
admin@raspberrypi:~/warden_terminal $ python3 node_warden.py
Traceback (most recent call last):
  File "node_warden.py", line 793, in store_local_ip
    pickle_it('save', 'ip.pkl', ip)
  File "node_warden.py", line 777, in pickle_it
    with open(filename, 'wb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/home/admin/warden_terminal/static/save/ip.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "node_warden.py", line 914, in <module>
    main()
  File "node_warden.py", line 800, in main
    store_local_ip()
  File "node_warden.py", line 795, in store_local_ip
    pickle_it('save', 'ip.pkl', None)
  File "node_warden.py", line 777, in pickle_it
    with open(filename, 'wb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/home/admin/warden_terminal/static/save/ip.pkl'
```

**Comment by pxsocs** [comment]
Fixed on next version (coming out in the next few minutes). It appears that the `/save` directory was not being cloned on some instances. Fixed with a check and auto mkdir:
```python
# Check if critical paths exist
Path(basedir + '/static/save').mkdir(parents=True, exist_ok=True)
```

**Comment by shawnyeager** [comment]
New errors on run:

```
✅  Background jobs running
last: cannot open /var/log/wtmp: No such file or directory
last: cannot open /var/log/wtmp: No such file or directory
last: cannot open /var/log/wtmp: No such file or directory
last: cannot open /var/log/wtmp: No such file or directory
Traceback (most recent call last):
  File "node_warden.py", line 919, in <module>
    main()
  File "node_warden.py", line 896, in main
    main_dashboard(config, tor)
  File "/home/admin/warden_terminal/dashboard.py", line 514, in main_dashboard
    main_loop.run()
  File "/home/admin/.local/lib/python3.7/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/home/admin/.local/lib/python3.7/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/home/admin/.local/lib/python3.7/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/home/admin/.local/lib/python3.7/site-packages/urwid/main_loop.py", line 823, in _loop
    alarm_callback()
  File "/home/admin/.local/lib/python3.7/site-packages/urwid/main_loop.py", line 173, in cb
    callback(self, user_data)
  File "/home/admin/warden_terminal/dashboard.py", line 428, in login_updater
    data = translate_text_for_urwid(data_login())
  File "/home/admin/warden_terminal/data.py", line 72, in data_login
    processes = subprocess.check_output("last")
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'last' returned non-zero exit status 1.
```

**Comment by shawnyeager** [comment]
Semi-related, but maybe better as a feature request is that it detects raspiblitz, but fails to see that Specter is installed:

```
⚡  Checking if running inside Raspiblitz Node ⚡
    RaspiBlitz Node Detected
    Switching Output to RaspiBlitz Monitor...

[i]  Checking if Specter Server 👻 is running
     Specter Server not found
```

**Comment by pxsocs** [comment]
Improved the error handling for when no users are found under the login files. This error should not be happening anymore.

**Comment by shawnyeager** [comment]
Getting closer.

![image](https://user-images.githubusercontent.com/980297/127746078-3127bdc5-fd61-40bd-9475-248eaf4eb789.jpeg)

**Comment by pxsocs** [comment]
For some reason, the `/var/log/wtmp` dir was not created during the Linux install. See info [here](https://askubuntu.com/questions/588367/should-var-log-wtmp-be-always-present-in-a-new-ubuntu-14-04-installation).

Try:
`mkdir /var/log/wtmp` 
and restart the app.

**Comment by pxsocs** [comment]
Made a few more changes to error handling. Closing this for now as I believe it will address most of these issues with permissions.
